# Railway Deployment Configuration
# Configures Python environment, PostgreSQL dependencies, and startup command

[phases.setup]
nixPkgs = ["...", "ffmpeg"]

[phases.install]
cmd = "pip install -r requirements.txt"

[start]
cmd = "cd backend && python main.py"