export const lightColors = {
  background: '#f4f4f8',
  card: '#ffffff',
  text: '#343a40',
  headerText: '#ffffff',
  primary: '#007bff',
  secondary: '#FF9500', // Using secondary for the orange button
  tertiary: '#AF52DE', // Using tertiary for the purple button
  border: '#e9ecef',
  error: '#dc3545',
  placeholder: '#6c757d',
  success: '#34C759',
  selectedCard: '#e3f2fd',
  disabled: '#ccc',
  // ChallengeCreationScreen specific
  warningBackground: '#fff3e0',
  warningText: '#e65100',
  warningAction: '#ff9800',
  successBackground: '#e8f5e8',
  successText: '#2e7d32',
  // GameScreen specific
  createChallengeCardBackground: '#e8f5e8',
  createChallengeCardBorder: '#4caf50',
  createChallengeCardText: '#2e7d32',
  errorBackground: '#ffebee',
  errorBorder: '#ffcdd2',
  networkErrorBackground: '#e3f2fd',
  networkErrorBorder: '#bbdefb',
  authErrorBackground: '#fff3e0',
  authErrorBorder: '#ffcc02',
  incorrect: '#f44336',
  videoPlayerBackground: '#000000',
  // StoreScreen specific
  storeHeroBackground: '#F5F5F5',
  storeSeparatorText: '#666666',
  storeBadgeText: '#FFFFFF',
  storeBadgeBackground: '#4CAF50',
  storeRestoreButtonBackground: '#6C757D',
  storeBalanceBackground: '#F8F9FA',
  storeBalanceText: '#495057',
  storePlanPrice: '#2196F3',
  storeSelectedPlanText: '#1976D2',
};

export const darkColors = {
  background: '#121212',
  card: '#1e1e1e',
  text: '#ffffff',
  headerText: '#ffffff',
  primary: '#007bff',
  secondary: '#FF9500',
  tertiary: '#C789E8',
  border: '#2c2c2c',
  error: '#dc3545',
  placeholder: '#6c757d',
  success: '#34C759',
  selectedCard: '#1a2a3a',
  disabled: '#444',
  // ChallengeCreationScreen specific
  warningBackground: '#2c241a',
  warningText: '#ffcc80',
  warningAction: '#ff9800',
  successBackground: '#1a2b1a',
  successText: '#a5d6a7',
  // GameScreen specific
  createChallengeCardBackground: '#1a2b1a',
  createChallengeCardBorder: '#81c784',
  createChallengeCardText: '#a5d6a7',
  errorBackground: '#2b1a1a',
  errorBorder: '#5c3333',
  networkErrorBackground: '#1a2a3a',
  networkErrorBorder: '#3a5a7a',
  authErrorBackground: '#2c241a',
  authErrorBorder: '#8c6d0d',
  incorrect: '#ef5350',
  videoPlayerBackground: '#000000',
  // StoreScreen specific
  storeHeroBackground: '#1a1a1a',
  storeSeparatorText: '#888888',
  storeBadgeText: '#ffffff',
  storeBadgeBackground: '#4CAF50',
  storeRestoreButtonBackground: '#484f58',
  storeBalanceBackground: '#222222',
  storeBalanceText: '#bbbbbb',
  storePlanPrice: '#2196F3',
  storeSelectedPlanText: '#64b5f6',
};